# Numpy

* 고성능의 수치 계산을 위해 제작된 python 라이브러리
* 벡터 및 행렬 연산에서의 편리한 기능을 제공


* numpy.ndarray 속성
  * ndarray.ndim
    * 배열의 차원
  * ndarray.shape
    * 배열의 크기를 나타내는 정수 튜플(행수, 열수)
  * ndarray.size
    * 배열의 요소의 총 갯수 (shape 요소의 곱과 같음)
  * ndarray.dtype
    * 배열의 data type

# Numpy array vs Python list

  * array
    * 선언하는 순간 데이터의 크기가 고정됨
    * 배열 내의 모든 데이터들의 형식은 같음
    * 데이터의 처리가 빠름
  * list
    * 선언 이후로도 컴퓨터는 리스트 내의 데이터 이외의 추가로 들어올 수 있는 데이터의 존재를 계산함
    * 리스트 내의 데이터 형식을 통일하지 않아도 됨

  * numpy를 사용하는 이유
    1. 메모리를 적게 차지
    2. 데이터 타입을 지정, 변경할 수 있음 (배열 통째로)
    3. 2.를 이용하여 코드를 최적화하기 좋음

In [1]:
import numpy as np

In [ ]:
scalar = 1

In [ ]:
vector = [1, 2, 3, 4]

In [ ]:
vector = np.array(vector, float)
vector

array([1., 2., 3., 4.])

In [ ]:
vector.shape # 배열 내 데이터의 모양

(4,)

In [ ]:
vector.dtype

dtype('float64')

In [ ]:
lst = [
    [[1, 2, 3],
    [4, 5, 6]],
]
arr = np.array(lst)
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
print(arr.size) # 배열 내 데이터의 갯수
print(arr.ndim) # 배열의 차원 수
print(arr.shape) # 배열의 모양
print(arr.shape[0]) # 배열의 1번 좌표의 (2차원에서는 행) 갯수
print(arr.shape[1]) # 배열의 2번 좌표의 (2차원에서는 열) 갯수
print(arr[0,0]) # 배열 내 원소 접근

6
3
(1, 2, 3)
1
2
[1 2 3]


In [ ]:
np.arange(10, 5, -1,float) # range 배열 생성

array([10.,  9.,  8.,  7.,  6.])

In [ ]:
np.zeros([3, 2]) # 영행렬 생성

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.eye(3) # 단위행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr1 = np.array([[1, 1],
               [2, 2]])
arr2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((arr1, arr2)) # 종방향으로 쌓기 (아래쪽으로 들어감)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((arr1, arr2)) # 횡방향으로 쌓기 (오른쪽으로 들어감)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
arr_v1 = np.array([[1, 1, 1], [2, 2, 2]])
arr_v1

array([[1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr_v2 = np.array([[3, 3, 3], [4, 4, 4], [5, 5, 5]])
arr_v2

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [ ]:
np.vstack((arr_v1, arr_v2)) # 행 수가 같아야 가능

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [ ]:
np.hstack((arr_v1, arr_v2)) # 행 수가 다르므로 hstack 불가능

ValueError: ignored

In [ ]:
arr_h1 = ([[1, 1, 1], [2, 2, 2]])
arr_h1

[[1, 1, 1], [2, 2, 2]]

In [ ]:
arr_h2 = ([[3, 3], [4, 4]])
arr_h2

[[3, 3], [4, 4]]

In [ ]:
np.vstack((arr_h1, arr_h2)) # 열 수가 다르므로 불가능

ValueError: ignored

In [ ]:
np.hstack((arr_h1, arr_h2)) # 열 수가 같아야 가능

array([[1, 1, 1, 3, 3],
       [2, 2, 2, 4, 4]])

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.base

In [ ]:
arr.shape

(20,)

In [ ]:
arr[:, np.newaxis].shape

(20, 1)

In [ ]:
np.expand_dims(arr, axis=1).shape

(20, 1)

In [ ]:
np.expand_dims(arr, axis = 0).shape

(1, 20)

In [ ]:
arr.resize((5, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
arr.reshape(4, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr.reshape(4, 5)
arr 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr = np.arange(20)
arr.dtype # array의 데이터 자료형 확인

dtype('int64')

In [ ]:
arr[1], arr[-1], arr[2]

(1, 19, 2)

In [ ]:
cond = (arr[::-1])

In [ ]:
cond = (arr >= 5)
arr[cond]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
np.any(arr >= 12)

True

In [ ]:
np.all(arr > 0)

True

In [ ]:
np.where(arr > 5, arr * 5, arr * -1)

array([[-1, -2, -3, -4],
       [-5, 30, 35, 40],
       [45, 50, 55, 60]])

In [ ]:
arr_2 = np.array([np.inf, np.nan, 3, 4, 5, np.nan, 6, 7])
arr_2

array([inf, nan,  3.,  4.,  5., nan,  6.,  7.])

In [ ]:
is_inf = np.isinf(arr_2)
np.any(is_inf), np.all(is_inf)

(True, False)

In [ ]:
np.isfinite(arr_2)

array([False, False,  True,  True,  True, False,  True,  True])

In [ ]:
arr_2[np.isfinite(arr_2) == False] = 0
arr_2

array([0., 0., 3., 4., 5., 0., 6., 7.])

In [ ]:
is_inf = np.isinf(arr_2)
np.any(is_inf), np.all(is_inf)

(True, False)

In [ ]:
is_nan = np.isnan(arr_2)
np.any(is_nan), np.all(is_nan)

(True, False)

In [ ]:
lst = [
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
arr.shape

(3, 3)

In [ ]:
mask = [True, False, True]
arr[:,mask]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
mask = arr > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
arr[mask]

array([6, 7, 8, 9])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
arr1 * arr2

array([2, 4, 6])

In [ ]:
arr1 = np.array([1, 2, 3])
arr1 * 2

array([2, 4, 6])

In [ ]:
arr1 = np.array([ # (4, 3)
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])
arr2 = np.array([1, 2, 3]) # (1, 3)
arr3 = np.array([[1], [2], [3], [4]]) # (4, 1)
arr1 + arr2, arr1 + arr3 # (4, 3) + (1, 3) , (4, 3) + (4, 1)

(array([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]]), array([[ 1,  1,  1],
        [12, 12, 12],
        [23, 23, 23],
        [34, 34, 34]]))

In [ ]:
arr1 = np.array([0, 10, 20, 30]) # np.newaxis로 (4, 1) -> (1, 4) 배열로 변경
arr2 = np.array([1, 2, 3])
arr1[:, np.newaxis] + arr2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
arr = np.array([1.53, "a", "b"]) # 문자열을 같이 집어넣으면 array가 통째로 바뀜
arr

array(['1.53', 'a', 'b'], dtype='<U32')